{
 "title": "Oversight",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(up{job=~\"$job\"},node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Status Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{job=\"node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Status Overview",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (application)(up{application!=\"\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (application)(up{application!=\"\"})"
    },
    {
     "expr": "sum by (application)(up) / count by (application)(up{application!=\"\"})"
    }
   ]
  },
  {
   "title": "Node Network usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp59s0\"}[$__rate_interval]) / (1024*1024)",
     "legendFormat": "down"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"enp59s0\"}[$__rate_interval]) / (1024*1024)",
     "legendFormat": "up"
    }
   ]
  }
 ]
}