---
- set_fact:
    appname: minio

- name: purge {{appname}} folders
  when: purge
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}
    state: absent

- name: Create {{appname}} folders
  when: appstate == 'started'
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'


- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "1000:1000"
    command: server /data --console-address ":9001"
    env:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    ports:
    labels: |
      {
        "traefik.http.services.{{appname}}.loadbalancer.server.port": "9001",
        "traefik.http.routers.{{appname}}.entrypoints": "https",
        "traefik.http.routers.{{appname}}.tls": "true"
      }
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/data:rw"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"

