---
- set_fact:
    appname: artemis

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "185"
    group: "185"
    mode: '0755'

- name: Create {{appname}} folders
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/config
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: "Manage artemis container state - {{appstate}} - {{ips.artemis}}"
  docker_container:
    name: "artemis"
    # image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.5
    image: "{{appconfig[appname].image}}"
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "185:185"
    command: 
    env:
      AMQ_USER: admin
      AMQ_PASSWORD: password
      AMQ_ROLE: admin
      AMQ_REQUIRE_LOGIN: "false"
      AMQ_ENABLE_METRICS_PLUGIN: "true"
      AMQ_JOURNAL_TYPE: "nio"
      AMQ_DATA_DIR: /artemisdata
    ports:
    labels: |
      {
        "traefik.enable": "true",
        "traefik.tcp.services.{{appname}}.loadbalancer.server.port": "61616",
        "traefik.tcp.routers.{{appname}}.entrypoints": "https",
        "traefik.tcp.routers.{{appname}}.tls": "true",
        "traefik.tcp.routers.{{appname}}.rule": "HostSNI(`{{appname}}.{{ansible_hostname}}.lan`)",
        "traefik.tcp.routers.{{appname}}.service": "{{appname}}",
        "traefik.http.services.{{appname}}-console.loadbalancer.server.port": "8161",
        "traefik.http.routers.{{appname}}-console.entrypoints": "http",
        "traefik.http.routers.{{appname}}-console.tls": "false",
        "traefik.http.routers.{{appname}}-console.rule": "Host(`{{appname}}-console.{{ansible_hostname}}.lan`)",
        "traefik.http.routers.{{appname}}-console.service": "{{appname}}-console"
      }
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/artemisdata:rw"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"
