---
- set_fact:
    appname: grafana-alpha

- name: provision infra
  ansible.builtin.include_role:
    name: cloud-native-appdev-lab-role
    tasks_from: infra-provision

- name: Template {{appname}} config
  when:  appconfig[appname].appstate == 'started'
  become: true
  ansible.builtin.template:
    src: templates/{{appname}}/config/grafana-datasources-template.j2
    dest: /home/{{ ansible_user }}/apps/{{appname}}/config/grafana-datasources.yml
    owner: "{{ appconfig[appname].exec_as_user }}"
    group: "{{ appconfig[appname].exec_as_group }}"
    mode: '0644'

- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    hostname: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{ appconfig[appname].appstate }}"
    recreate: "{{ appconfig[appname].recreate }}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "{{ appconfig[appname].exec_as_user }}:{{ appconfig[appname].exec_as_group }}"
    ports: "{{ appconfig[appname].ports | default(omit,true)}}"

    command: 
    env:
      GF_SERVER_DOMAIN: "{{ appname }}.{{ inventory_hostname }}"
      GF_SERVER_ROOT_URL: "https://{{ appname }}.{{ inventory_hostname }}/"
      GF_PLUGINS_ENABLE_ALPHA: "true"
      GF_AUTH_BASIC_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Keycloak OIDC / OAuth 2.0"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ appname }}.{{ inventory_hostname }}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "MjqkTs9Hr0I96NcJ17K2idIepC26SWT0"
      GF_AUTH_GENERIC_OAUTH_SCOPES: profile
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://keycloak.{{ inventory_hostname }}/realms/apps/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://keycloak.{{ inventory_hostname }}/realms/apps/protocol/openid-connect/token"
      GF_AUTH_GENERIC_OAUTH_ID_TOKEN_ATTRIBUTE_NAME: "access_token"
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: "preferred_username"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://keycloak.{{ inventory_hostname }}/realms/apps/protocol/openid-connect/userinfo"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://keycloak.{{ inventory_hostname }}/realms/apps/protocol/openid-connect/logout"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(realm_access.roles[*], 'o11y-admin') && 'Admin' || contains(realm_access.roles[*], 'o11y-editor') && 'Editor' || 'Viewer'"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT: "true"
      GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: "groups[*]"
      GF_PATHS_DATA: "/data"
      GF_PATHS_LOGS: "/data/logs"
      GF_PATHS_PLUGINS: "/plugins"
    labels: |
      {
        "traefik.http.services.{{appname}}.loadbalancer.server.port": "3000",
        "traefik.http.routers.{{appname}}.service": "{{appname}}",
        "traefik.http.routers.{{appname}}.entrypoints": "https",
        "traefik.http.routers.{{appname}}.tls": "true",
        "traefik.http.routers.{{appname}}.rule": "Host(`{{appname}}.{{inventory_hostname}}`)",
      }
    volumes:
      - /home/{{ansible_user}}/apps/{{ appname }}/config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml:ro
      - /home/{{ansible_user}}/apps/{{ appname }}/config/dashboards:/etc/grafana/provisioning/dashboards:ro
      - /home/{{ansible_user}}/apps/{{ appname }}/config/plugins:/plugins:ro
      - /home/{{ansible_user}}/apps/{{ appname }}/config/graphics:/usr/share/grafana/public/graphics:ro
      - /home/{{ansible_user}}/apps/tls/{{inventory_hostname}}-root-ca.pem:/etc/ssl/certs/ca-certificates.crt:ro
      - /home/{{ansible_user}}/apps/{{ appname }}/data/:/data:rw
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"

- name: Check if server is up
  when:  appconfig[appname].appstate == 'started'
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/health"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 2

- name: Reset password
  when:  appconfig[appname].appstate == 'started'
  ignore_errors: true
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/user/password"
    user: "admin"
    password: "admin"
    method: PUT
    body: |
      {
        "oldPassword": "admin",
        "newPassword": "password"
      }
    force_basic_auth: yes
    status_code: 200
    headers:
      Content-Type: application/json
      accept: application/json


- name: Create team
  when:  appconfig[appname].appstate == 'started'
  ignore_errors: true
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/teams"
    user: "admin"
    password: "password"
    method: POST
    body_format: json
    body: | 
      {
        "name": "{{ item.name }}",
        "email": "{{ item.name }}@lab.local",
        "orgId": 1
      }
    force_basic_auth: yes
    status_code: 200
  loop:
    - id: 1
      name: teamadmin
    - id: 2
      name: egypt
    - id: 3
      name: greece
    - id: 4
      name: sre
    - id: 5
      name: frontend
    - id: 6
      name: backend


- name: Create folder
  when:  appconfig[appname].appstate == 'started'
  ignore_errors: true
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/folders"
    user: "admin"
    password: "password"
    method: POST
    body_format: json
    body: | 
      {
        "uid": "{{ item.name }}",
        "title": "{{ item.name }}"
      }
    force_basic_auth: yes
    status_code: 200
  loop:
    - id: 1
      name: teamadmin
    - id: 2
      name: egypt
    - id: 3
      name: greece
    - id: 4
      name: sre
    - id: 5
      name: frontend
    - id: 6
      name: backend

- name: delete infra
  ansible.builtin.include_role:
    name: cloud-native-appdev-lab-role
    tasks_from: infra-delete