---
- set_fact:
    appname: grafana-enterprise

- name: purge {{appname}} folders
  when: purge
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}
    state: absent

- name: Create {{appname}} folders
  when: appstate == 'started'
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/config/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy config {{appname}} config
  when: appstate == 'started'
  copy:
    src: "templates/grafana/config/"
    dest: /home/{{ ansible_user }}/apps/{{appname}}/config/
    mode: '0644'

- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "1000:1000"
    command: 
    env:
      GF_SERVER_DOMAIN: "{{ appname }}.{{ inventory_hostname }}"
      GF_SERVER_ROOT_URL: https://{{ appname }}.{{ inventory_hostname }}/
      GF_ENTERPRISE_LICENSE_TEXT: "{{ secretappconfig[appname].license }}"
      GF_AUTH_BASIC_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_AUTH_OAUTH_AUTO_LOGIN: "false"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "Keycloak OIDC / OAuth 2.0"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "{{ appname }}.{{ inventory_hostname }}"
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "e2dt6BF1roELLGmksmArt9aIgm7jB6lB"
      GF_AUTH_GENERIC_OAUTH_SCOPES: profile
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://keycloak.{{ inventory_hostname }}/realms/apps/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://keycloak.{{ inventory_hostname }}/realms/apps/protocol/openid-connect/token"
      GF_AUTH_GENERIC_OAUTH_ID_TOKEN_ATTRIBUTE_NAME: "access_token"
      GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: "preferred_username"
      GF_AUTH_GENERIC_OAUTH_API_URL: "https://keycloak.{{ inventory_hostname }}/realms/apps/protocol/openid-connect/userinfo"
      GF_AUTH_SIGNOUT_REDIRECT_URL: "https://keycloak.{{ inventory_hostname }}/realms/apps/protocol/openid-connect/logout"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(realm_access.roles[*], 'o11y-admin') && 'Admin' || contains(realm_access.roles[*], 'o11y-editor') && 'Editor' || contains(realm_access.roles[*], 'o11y-viewer') && 'Viewer'"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT: "true"
      GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: "groups[*]"
      GF_USERS_EDITORS_CAN_ADMIN: "true"
      GF_WHITE_LABELING_LOGIN_BACKGROUND: "url(public/branding/background.jpg)"
      GF_WHITE_LABELING_LOGIN_LOGO: "public/branding/logo.svg"
      GF_WHITE_LABELING_MENU_LOGO: "public/branding/logo.svg"
    ports:
    labels: |
      {
        "traefik.http.routers.{{appname}}.entrypoints": "https",
        "traefik.http.routers.{{appname}}.tls": "true"
      }
    volumes:
      - /home/{{ansible_user}}/apps/{{ appname }}/config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/grafana-datasources.yml:ro
      - /home/{{ansible_user}}/apps/{{ appname }}/config/dashboards:/etc/grafana/provisioning/dashboards:ro
      - /home/{{ansible_user}}/apps/{{ appname }}/config/rbac/rbac.yml:/etc/grafana/provisioning/access-control/rbac.yml:ro
      - /home/{{ansible_user}}/apps/{{ appname }}/config/branding:/usr/share/grafana/public/branding:ro
      - /home/{{ansible_user}}/apps/{{ appname }}/config/graphics:/usr/share/grafana/public/graphics:ro
      - /home/{{ansible_user}}/apps/tls/{{inventory_hostname}}-root-ca.pem:/etc/ssl/certs/ca-certificates.crt:ro
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"

- name: Check if server is up
  when: appstate == 'started'
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/health"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 2

- name: Reset password
  when: appstate == 'started'
  ignore_errors: true
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/user/password"
    user: "admin"
    password: "admin"
    method: PUT
    body: |
      {
        "oldPassword": "admin",
        "newPassword": "password"
      }
    force_basic_auth: yes
    status_code: 200
    headers:
      Content-Type: application/json
      accept: application/json

- name: Create team
  when: appstate == 'started'
  ignore_errors: true
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/teams"
    user: "admin"
    password: "password"
    method: POST
    body_format: json
    body: | 
      {
        "name": "{{ item.name }}",
        "email": "{{ item.name }}@lab",
        "orgId": 1
      }
    force_basic_auth: yes
    status_code: 200
  loop:
    - id: 1
      name: egypt
    - id: 2
      name: greece

- name: Create team sync
  when: appstate == 'started'
  ignore_errors: true
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/teams/{{ item.id }}/groups"
    user: "admin"
    password: "password"
    method: POST
    body_format: json
    body: |
      {
        "groupId": "/{{ item.name }}"
      }
    force_basic_auth: yes
    status_code: 200
  loop:
    - id: 1
      name: egypt
    - id: 2
      name: greece

- name: Create teamadmin team
  when: appstate == 'started'
  ignore_errors: true
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/teams"
    user: "admin"
    password: "password"
    method: POST
    body_format: json
    body: | 
      {
        "name": "{{ item.name }}",
        "email": "{{ item.name }}@lab",
        "orgId": 1
      }
    force_basic_auth: yes
    status_code: 200
  loop:
    - id: 3
      name: teamadmin

- name: Create team
  when: appstate == 'started'
  ignore_errors: true
  uri:
    url: "https://{{appname}}.{{inventory_hostname}}/api/access-control/teams/{{ item.id }}/roles"
    user: "admin"
    password: "password"
    method: POST
    body_format: json
    body: | 
      {
          "roleUid": "teamadmin"
      }
    force_basic_auth: yes
    status_code: 200
  loop:
    - id: 3
      name: teamadmin