---
- set_fact:
    appname: reposilite

- name: purge {{appname}} folders
  when: purge
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}
    state: absent

- name: Create {{appname}} folders
  when: appstate == 'started'
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "1000"
    group: "1000"
    mode: '0755'


- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user:
    command:
    env:
      JAVA_OPTS: "-Xmx64M"
      REPOSILITE_OPTS: --token admin:password
    ports:
    labels: |
      {
        "traefik.http.routers.{{appname}}.entrypoints": "https",
        "traefik.http.routers.{{appname}}.tls": "true",
        "traefik.http.services.{{appname}}.loadbalancer.server.port": "8080"
      }
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/app/data:rw"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"