---
- set_fact:
    appname: traefik

- name: purge {{appname}} folders
  when: purge
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}
    state: absent

- name: Create {{appname}} folders
  when: appstate == 'started'
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/config/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Template {{appname}} config
  when: appstate == 'started'
  ansible.builtin.template:
    src: templates/{{appname}}/config/traefik.ansible.template.yml
    dest: /home/{{ ansible_user }}/apps/{{appname}}/config/traefik.yml
    mode: '0644'

- name: Template {{appname}} tls
  when: appstate == 'started'
  ansible.builtin.template:
    src: templates/{{appname}}/config/tls.ansible.template.j2
    dest: /home/{{ ansible_user }}/apps/{{appname}}/config/tls.yml
    mode: '0644'

- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    # user: "1000:1000"
    command:
    env:
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    labels: 
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/config/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/home/{{ansible_user}}/apps/{{appname}}/config/tls.yml:/config/tls.yml:ro"
      - "/home/{{ansible_user}}/apps/tls:/certs:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"