---
- set_fact:
    appname: promtail

- name: purge {{appname}} folders
  when: purge
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}
    state: absent

- name: Create {{appname}} folders
  when: appstate == 'started'
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/config/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Template {{appname}} config
  when: appstate == 'started'
  ansible.builtin.template:
    src: templates/{{appname}}/config/config.template.j2
    dest: /home/{{ ansible_user }}/apps/{{appname}}/config/config.yml
    mode: '0644'

- name: Create {{appname}} folders
  when: appstate == 'started'
  become: true
  file:
    path: /home/{{ ansible_user }}/apps/{{appname}}/data
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: "Manage {{appname}} container state - {{appstate}} - {{appconfig[appname].ip}}"
  docker_container:
    name: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{appstate}}"
    recreate: "{{recreate}}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    # user: "1000:1000"
    command: 
      - -config.file=/mnt/config/config.yml
    env:
    ports:
    labels: |
      {
        "traefik.http.routers.{{appname}}.entrypoints": "https",
        "traefik.http.routers.{{appname}}.tls": "true",
        "traefik.http.services.{{appname}}.loadbalancer.server.port": "80"
      }
    volumes:
      - /home/{{ ansible_user }}/apps/{{appname}}/config/config.yml:/mnt/config/config.yml:ro
      - /home/{{ ansible_user }}/apps/{{appname}}/data/:/var/log/:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"