---
- set_fact:
    appname: artemis

- name: provision infra
  ansible.builtin.include_role:
    name: cloud-native-appdev-lab-role
    tasks_from: infra-provision

- name: "Manage artemis container state - {{appstate}} - {{ips.artemis}}"
  docker_container:
    name: "{{appname}}"
    hostname: "{{appname}}"
    image: "{{appconfig[appname].image}}"
    state: "{{ appconfig[appname].appstate }}"
    recreate: "{{ appconfig[appname].recreate }}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    detach: true
    user: "{{ appconfig[appname].exec_as_user }}:{{ appconfig[appname].exec_as_group }}"
    ports: "{{ appconfig[appname].ports | default(omit,true)}}"

    command: 
    env:
      JAVA_APPEND_ARG: "-Xms64M -Xmx128M"
    labels: |
      {
        "traefik.enable": "true",
        "traefik.tcp.services.{{appname}}.loadbalancer.server.port": "61616",
        "traefik.tcp.routers.{{appname}}.service": "{{appname}}",
        "traefik.tcp.routers.{{appname}}.entrypoints": "https",
        "traefik.tcp.routers.{{appname}}.tls": "true",
        "traefik.tcp.routers.{{appname}}.rule": "HostSNI(`{{appname}}.{{inventory_hostname}}`)",
        
        "traefik.http.services.{{appname}}-console.loadbalancer.server.port": "8161",
        "traefik.http.routers.{{appname}}-console.service": "{{appname}}-console"
        "traefik.http.routers.{{appname}}-console.entrypoints": "http",
        "traefik.http.routers.{{appname}}-console.tls": "false",
        "traefik.http.routers.{{appname}}-console.rule": "Host(`{{appname}}-console.{{inventory_hostname}}`)",
      }
    volumes:
      - "/home/{{ansible_user}}/apps/{{appname}}/data:/home/appuser/broker/data:rw"
    networks_cli_compatible: yes
    network_mode: primenet
    networks:
      - name: primenet
        ipv4_address: "{{appconfig[appname].ip}}"

- name: Check if server is up
  when:  appconfig[appname].appstate == 'started'
  uri:
    url: "http://{{appname}}-console.{{inventory_hostname}}/metrics"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 2

- name: delete infra
  ansible.builtin.include_role:
    name: cloud-native-appdev-lab-role
    tasks_from: infra-delete