---
- set_fact:
    application: "{{ apps[rolesvar] }}"


- name: create docker manifest
  shell: | 
     docker manifest create {{ item[1] }}/{{ application.artifactId }}:{{ application.buildVersion }} -a {{ item[1] }}/{{ application.artifactId }}:{{ application.buildVersion }}-{{ item[0] }}
  loop: "{{ ( application.arch ) | product(application.registries) }}"

- name: create push multi arch manifest
  shell: | 
    docker manifest push {{ item }}/{{ application.artifactId }}:{{ application.buildVersion }}
  loop: "{{  application.registries   }}"