---
- set_fact:
    application: "{{ apps[rolesvar] }}"


- name: create docker manifest
  shell: | 
     docker manifest create {{ application.1.1 }}/{{ application.0.0.artifactId }}:{{ application.0.0.buildVersion }} -a {{ application.1.1 }}/{{ application.0.0.artifactId }}:{{ application.0.0.buildVersion }}-{{ application.0.1 }}
  loop: "{{ ( application | subelements('arch') ) | product(application | subelements('registries')) | list   }}"

- name: create push multi arch manifest
  shell: | 
    docker manifest push {{ application.1 }}/{{ application.0.artifactId }}:{{ application.0.buildVersion }}
  loop: "{{  application | subelements('registries')   }}"