---

- name: Copy custom scripts
  become: true
  copy:
    src: "templates/kvm-scripts/{{item}}"
    dest: /usr/local/bin/
    mode: "0755"
  with_items:
    - dvm
    - kvsh 
    - lsvm
    - vmcreate
    - vmcreate-rhel