---
- name: Base server packages
  become: true
  apt:
    name: 
      - git
      - ansible
      - docker.io
      - python3-docker
      - apparmor
      - tmux
      - vim
      - openjdk-17-jdk-headless
      - prometheus-node-exporter
      - curl
      - rsync
      - dnsmasq
      - ncdu
      - dnsutils
      - bmon
    state: present
# sudo apt install git ansible docker.io docker-compose apparmor tmux vim openjdk-17-jdk-headless prometheus-node-exporter curl rsync dnsmasq ncdu npm python3-docker
# sudo apt install git ansible docker.io vim openjdk-17-jdk-headless prometheus-node-exporter curl rsync dnsmasq ncdu python3-docker dnsutils bmon


# - name: Network manager
#   become: true
#   when: globaldnsserver is undefined or globaldnsserver == false
#   apt:
#     name: 
#       - network-manager
#     state: present

# by default we do not start dnsmasq service
- name: disable dnsmasq service
  become: true
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: dnsmasq

# by default we do not start resolved service
- name: disable dnsmasq service
  become: true
  ansible.builtin.systemd:
    enabled: false
    state: stopped
    name: systemd-resolved

- name: systemd-resolved
  become: true
  when: globaldnsserver is undefined or globaldnsserver == false
  shell: |
    rm /etc/resolv.conf
    touch /etc/resolv.conf
