---
- set_fact:
    appname: "{{ rolesvar }}"

- set_fact:
    imagetag: "{{ docker.pullregistry }}/{{ appconfig[appname].image | regex_replace('.*/(.*)','\\1')  }}"

- name: debug
  debug:
    msg: "{{ imagetag }}"

- name: pulling
  shell: |
    docker pull {{ imagetag }}
