{
 "title": "Apache Camel - Context view",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(CamelRoutesRunning_routes{eventType=\"RouteEvent\"},job)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(CamelRoutesRunning_routes{eventType=\"RouteEvent\",job=~\"${job}\"},namespace)"
    }
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": {
     "query": "label_values(CamelRoutesRunning_routes{eventType=\"RouteEvent\",job=~\"${job}\",namespace=\"$namespace\"},camelContext)"
    }
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": {
     "query": "label_values(CamelExchangesSucceeded_total{job=~\"${job}\",namespace=\"$namespace\",camelContext=\"$context\"},routeId)"
    }
   },
   {
    "name": "processor",
    "label": "Camel Processor",
    "query": {
     "query": "label_values(CamelMessageHistory_seconds_count{job=~\"${job}\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"},nodeId)"
    }
   },
   { "name": "app_label", "label": "Application Label", "query": "application" },
   {
    "name": "app",
    "label": "Application Name",
    "query": {
     "query": "label_values(CamelRoutesRunning_routes{job=~\"$job\",eventType=\"RouteEvent\",camelContext=\"$context\"},$app_label)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Stats Camel Context : $context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Routes Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (CamelRoutesRunning_routes{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\"})",
     "legendFormat": "Instances"
    },
    {
     "expr": "sum(CamelRoutesRunning_routes{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\"}) / sum(CamelRoutesAdded_routes{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\"})*100",
     "legendFormat": "Running"
    },
    {
     "expr": "max(CamelRoutesAdded_routes{job=\"$job\",namespace=\"$namespace\",camelContext=\"$context\"})",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "description": "Shows completed exchanges of the camel context in the time range",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(CamelExchangesTotal_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (camelContext) (increase(CamelExchangesFailed_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (camelContext) (increase(CamelExchangesFailed_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\"}[$__range])) / sum by (camelContext) (increase(CamelExchangesTotal_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation : CPU Usage by node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node_name) (process_cpu_usage{job=~\"$job\",namespace=\"$namespace\",$app_label=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation : Memory usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name,$app_label) (jvm_memory_used_bytes{job=~\"$job\",namespace=\"$namespace\",$app_label=~\"$app\", area=\"heap\"}) / sum by (kubernetes_pod_name,$app_label) (jvm_memory_max_bytes{job=~\"$job\",namespace=\"$namespace\",$app_label=~\"$app\", area=\"heap\"})",
     "legendFormat": "{{kubernetes_pod_name}} heap"
    },
    {
     "expr": "sum by (kubernetes_pod_name,$app_label) (jvm_memory_used_bytes{job=~\"$job\",namespace=\"$namespace\",$app_label=~\"$app\", area=\"nonheap\"}) / sum by (kubernetes_pod_name,$app_label) (jvm_memory_max_bytes{job=~\"$job\",namespace=\"$namespace\",$app_label=~\"$app\", area=\"nonheap\"})",
     "legendFormat": "{{kubernetes_pod_name}} nonheap"
    }
   ]
  },
  {
   "title": "Pods per Nodes and CPU Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (node_name) (CamelRoutesRunning_routes{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\"})\n"
    },
    {
     "expr": "sum by (node_name) (process_cpu_usage{job=~\"$job\",namespace=\"$namespace\",$app_label=~\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inflight",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(CamelExchangesInflight{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Camel Context Overview - RED Method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Rate : Executions / sec",
   "type": "stat",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (irate(CamelExchangesTotal_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]))",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Duration : Avg Execution time",
   "type": "stat",
   "gridPos": { "h": 13, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (increase (CamelRoutePolicy_seconds_sum{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) \n \n/ \n \nsum by (routeId) (increase (CamelRoutePolicy_seconds_count{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors : Failure Rates",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (routeId) (increase(CamelExchangesFailed_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) / sum by (routeId) (increase(CamelExchangesTotal_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "Traffic Per Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ex/sec $route",
     "type": "stat",
     "description": "Show the numbers of exchanges per second for a camel route",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(CamelExchangesTotal_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "$route Exchanges/sec - all instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (camelContext) (irate(CamelExchangesTotal_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$route  Exchanges/sec - per instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (irate(CamelExchangesTotal_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$route Failure % - all instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 12, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (routeId) (increase(CamelExchangesFailed_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) / sum by (routeId) (increase(CamelExchangesTotal_total{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Inflight $route",
     "type": "stat",
     "description": "Current number of inflight exchanges",
     "gridPos": { "h": 5, "w": 2, "x": 17, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (camelContext) (CamelExchangesInflight{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "$route Inflight  - per instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (CamelExchangesInflight{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Execution Times Per Route",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg Exec time $route",
     "type": "stat",
     "description": "Average execution time for a route",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 23 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (camelContext) (increase (CamelRoutePolicy_seconds_sum{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) \n \n/ \n \nsum by (camelContext) (increase (CamelRoutePolicy_seconds_count{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Exec time $route - all instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 2, "y": 23 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (camelContext) (increase (CamelRoutePolicy_seconds_sum{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) \n \n/ \n \nsum by (camelContext) (increase (CamelRoutePolicy_seconds_count{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Exec time $route - per instances",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 5, "x": 7, "y": 23 },
     "repeat": "route",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (kubernetes_pod_name) (increase (CamelRoutePolicy_seconds_sum{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range])) \n \n/ \n \nsum by (kubernetes_pod_name) (increase (CamelRoutePolicy_seconds_count{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[$__range]))",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Processor Execution Times - $route",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "repeat": "route",
     "targets": [
      {
       "expr": "sum by (routeId,nodeId) (increase (CamelMessageHistory_seconds_sum{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\",nodeId=~\"$processor\"}[$__range])) \n/ \nsum by (routeId,nodeId) (increase (CamelMessageHistory_seconds_count{job=~\"$job\",namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\",nodeId=~\"$processor\"}[$__range]))\n"
      }
     ]
    }
   ]
  }
 ]
}