{
 "title": "Quarkus Camel Dashboard - Context View",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(application_camel_context_exchanges_completed_total,namespace)"
    }
   },
   {
    "name": "context",
    "label": "Camel Context",
    "query": {
     "query": "label_values(application_camel_context_exchanges_completed_total{namespace=\"$namespace\"},camelContext)"
    }
   },
   {
    "name": "route",
    "label": "Camel Route",
    "query": {
     "query": "label_values(application_camel_route_exchanges_completed_total{namespace=\"$namespace\",camelContext=\"$context\"},routeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Global Stats Camel Context : $context",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of parallel instances running",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (application_camel_context_exchanges_completed_total{namespace=\"$namespace\",camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Routes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(1,application_camel_route_count{namespace=\"$namespace\",camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Consumers Inflight",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(application_camel_context_exchanges_inflight_count{namespace=\"$namespace\",camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "stat",
   "description": "Shows completed exchanges of the camel context",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (application_camel_context_exchanges_completed_total{namespace=\"$namespace\",camelContext=\"$context\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "description": "Shows failed exchanges of the camel context",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (application_camel_context_exchanges_failed_total{namespace=\"$namespace\",camelContext=\"$context\"})"
    }
   ]
  },
  { "title": "Traffic Per Route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Ex/sec $route",
   "type": "stat",
   "description": "Show the numbers of exchanges per second for a camel route",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(application_camel_route_exchanges_completed_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[30s]))"
    }
   ]
  },
  {
   "title": "$route Exchanges/sec - all instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 5 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context) (irate(application_camel_route_exchanges_completed_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[30s]))",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route  Exchanges/sec - per instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 5 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(application_camel_route_exchanges_completed_total{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}[30s])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inflight $route",
   "type": "stat",
   "description": "Current number of inflight exchanges",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 5 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (application_camel_route_exchanges_inflight_count{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})"
    }
   ]
  },
  {
   "title": "$route Inflight  - all instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (context)  (application_camel_route_exchanges_inflight_count{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})",
     "legendFormat": "{{context}}"
    }
   ]
  },
  {
   "title": "$route Inflight  - per instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (application_camel_route_exchanges_inflight_count{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Execution Times Per Route Since Start",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Avg Exec time $route",
   "type": "stat",
   "description": "Average execution time for a route",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 11 },
   "repeat": "route",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (sum by (kubernetes_pod_name)(application_camel_route_processing_seconds_count{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})*sum by (kubernetes_pod_name)(application_camel_route_processing_mean_seconds{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})) / sum (application_camel_route_processing_seconds_count{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - all instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 2, "y": 11 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (sum by (kubernetes_pod_name)(application_camel_route_processing_seconds_count{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})*sum by (kubernetes_pod_name)(application_camel_route_processing_mean_seconds{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})) / sum (application_camel_route_processing_seconds_count{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"})"
    }
   ]
  },
  {
   "title": "Avg Exec time $route - per instances",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 11 },
   "repeat": "route",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_camel_route_processing_mean_seconds{namespace=\"$namespace\",camelContext=\"$context\",routeId=~\"$route\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}