multitenancy_enabled: false

ingester:
  ring:
    min_ready_duration: 1s
    replication_factor: 1

blocks_storage:
  backend: s3
  s3:
    endpoint: minio:9000
    bucket_name: mimir-tsdb
    access_key_id: admin
    secret_access_key: password
    insecure: true
  tsdb:
    dir: /data/tsdb/
  bucket_store:
    sync_dir: /data/tsdb-sync/

memberlist:
  join_members: [ mimir ]

activity_tracker:
  filepath: /data/metrics-activity.log

ruler: 
  rule_path: /data/data-ruler/

ruler_storage:
  backend: s3
  s3:
    endpoint: minio:9000
    bucket_name: mimir-ruler
    access_key_id: admin
    secret_access_key: password
    insecure: true

compactor:
  data_dir: /data/data-compactor/

server:
  log_level: info
  http_listen_port: 9090

