#jinja2:variable_start_string:'{{[', variable_end_string:']}}'
## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.{{[ inventory_hostname ]}}`)"
    exposedByDefault: true
  file:
    filename: "/config/tls.yml"
    watch: true

# API and dashboard configuration
api:
  insecure: true

entryPoints:
  http:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: https
    #       scheme: https
  https:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    
# log:
#   level: DEBUG